defaults:
  - data: audioset20k_pretrain
  - data_augm: cav_augm
  - backbone: cav
  - criterion: va_vam
  - optim: adam
  - train_algo: pretrain
  - cl_algo: finetune_submodule
  - environment: default
  - hydra: default
  - logging: default
